version: 2
updates:
  # Configuration for NuGet
  - package-ecosystem: "nuget"
    directory: "/QRBarcodeApp"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - ".NET"
      - "automerge"

  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/QRBarcodeApp"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
      - "automerge"
