name: Dependabot auto-merge

on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Debug metadata
        run: |
          echo "Dependency Names: ${{ steps.metadata.outputs.dependency-names }}"
          echo "Update Type: ${{ steps.metadata.outputs.update-type }}"
          echo "Labels: ${{ github.event.pull_request.labels }}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"

      - name: Verify Dependabot actor
        run: |
          if [[ "${{ github.event.sender.type }}" != "Bot" || "${{ github.event.sender.login }}" != "dependabot[bot]" ]]; then
            echo "This PR is not from Dependabot. Exiting."
            exit 1
          fi

      - name: Enable auto-merge for Dependabot PRs
        if: contains(github.event.pull_request.labels.*.name, 'automerge')
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
